language: R
sudo: false

cache:
  packages: yes

r:
  - oldrel
  - release
  - devel

install:
- R -e 'install.packages("devtools")'
- R -e 'install.packages("igraph")'
- R -e 'install.packages("jsonlite")'
- R -e 'install.packages("formatR")'
- R -e 'devtools::install_deps("ProvTools/provR", dep = TRUE)'

script:
- R CMD build .
- R CMD check --as-cran *tar.gz
