language: R
sudo: false

cache:
  packages: yes

r:
  - oldrel
  - release
  - devel

install:
- R -e 'install.packages("devtools")'
- R -e 'devtools::install_deps("ProvTools/provR")'

script:
- R CMD build .
- R CMD check --as-cran *tar.gz
